import type { Metadata } from "next";
import "./globals.css";
import Logos from "./components/logos";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gradient-to-br from-green-50 to-emerald-50 items-center py-8 px-4">
        <div className="flex-grow flex flex-col justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
